# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    ENV["FASTLANE_PASSWORD"] = "Oms20190211!"
    ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "tshy-tbcr-mbzw-ryvr"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"
  end
  desc "Push a new beta build to TestFlight"
  lane :beta do
  get_certificates           
  get_provisioning_profile
    increment_build_number(xcodeproj: "OMPASS.xcodeproj")
    build_app(workspace: "OMPASS.xcworkspace", scheme: "OMPASS")
    upload_to_testflight
  end
end
